// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrzJT8d301_E52mj7G25uY2Ti37ujnU2o',
    appId: '1:965114787977:web:56d69aec679c298ac0ee58',
    messagingSenderId: '965114787977',
    projectId: 'learntraintest-50cff',
    authDomain: 'learntraintest-50cff.firebaseapp.com',
    storageBucket: 'learntraintest-50cff.appspot.com',
    measurementId: 'G-HD9M50CDCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYl_WXm_FM0ks0Vi2s5UEL_sbM8iC5DCg',
    appId: '1:965114787977:android:cf05ceb7d027cac0c0ee58',
    messagingSenderId: '965114787977',
    projectId: 'learntraintest-50cff',
    storageBucket: 'learntraintest-50cff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8vmTLq1cZvbuVfeXvGxNGYF1p2OesiYM',
    appId: '1:965114787977:ios:8f520d227c605ee1c0ee58',
    messagingSenderId: '965114787977',
    projectId: 'learntraintest-50cff',
    storageBucket: 'learntraintest-50cff.appspot.com',
    iosClientId: '965114787977-qr32ir8jrt3jmjalfgd6h8fmld8racru.apps.googleusercontent.com',
    iosBundleId: 'com.example.fapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8vmTLq1cZvbuVfeXvGxNGYF1p2OesiYM',
    appId: '1:965114787977:ios:9976002ceb64cf4bc0ee58',
    messagingSenderId: '965114787977',
    projectId: 'learntraintest-50cff',
    storageBucket: 'learntraintest-50cff.appspot.com',
    iosClientId: '965114787977-dnu1tend3l603e3r84jp84o74q81pkq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fapp1.RunnerTests',
  );
}
